# -*- coding: utf-8 -*-
"""The 88 original affirmations, in eight named families of eleven.
Shared source for the workbook pages, the 32 printable cards and the
12 phone wallpapers. Grounded, believable, agency-centered; no guaranteed
outcomes, no toxic positivity."""

AFFIRMATIONS = {
 "Abundance": [
   "There is more than one way for good things to reach me.",
   "I can want more and be grateful at the same time.",
   "Money is a tool I am learning to hold with steadier hands.",
   "Enough is a place I can visit today, not only a finish line.",
   "I am building a life with room in it: room to rest, room to receive.",
   "Small surpluses count; I notice them and let them count.",
   "I can look at my numbers without flinching, and looking is power.",
   "What I tend tends to grow, and I am tending my own field now.",
   "Plenty does not require my exhaustion as payment.",
   "I make room for a life that fits me.",
   "Abundance, for me, includes time, ease and people I can exhale around.",
 ],
 "Worthiness": [
   "I do not have to audition for my own life.",
   "My needs are information, not impositions.",
   "I was never required to earn rest, and I am done invoicing myself for it.",
   "Being a work in progress does not lower my worth.",
   "I can be given to without owing a performance in return.",
   "The care I give so freely is care I am also allowed to keep.",
   "My presence adds something before I produce anything.",
   "I belong in rooms I used to only clean up after.",
   "Softness and worth can live in the same woman.",
   "I am allowed to take up the space my life actually needs.",
   "Good things suit me; I am practicing believing that.",
 ],
 "Courage": [
   "Courage can be quiet and consistent.",
   "I can be afraid and in motion at the same time.",
   "Being seen is a risk I am learning to afford.",
   "My voice does not need permission slips it never receives.",
   "I would rather be known than be comfortable and invisible.",
   "Five percent braver, repeated, becomes a different life.",
   "Fear gets a seat in the car, never the wheel.",
   "I can survive being misunderstood on my way to being clear.",
   "The stakes of staying small are higher than they look.",
   "I let my work be witnessed before it is perfect.",
   "Every brave thing I have done was once the thing I avoided.",
 ],
 "Self-Trust": [
   "I keep small promises to myself, and they are adding up.",
   "My judgment has gotten me through every day so far.",
   "I can change my mind without losing my footing.",
   "The next honest step is enough navigation for today.",
   "I trust the next honest step.",
   "When I do not know, I can find out; not-knowing is a stage, not a verdict.",
   "My pace is a rhythm, not a report card.",
   "I have recovered before, and recovering is a skill I keep.",
   "I can hear my own voice underneath everyone else's advice.",
   "Decisions I make with clear eyes tend to hold.",
   "I am someone I can rely on, and I have the receipts.",
 ],
 "Love": [
   "I can receive love without abandoning myself.",
   "The love I want is mutual, steady and unconfusing.",
   "I bring warmth to my relationships without setting myself on fire.",
   "Being easy to love was never the assignment; being honest is.",
   "My standards are not walls; they are doors with working locks.",
   "I let people show me who they are, and I believe them.",
   "Connection that costs my peace is priced too high.",
   "I am learning to let care in without checking for the catch.",
   "The way I speak to myself sets the tone for what I accept.",
   "I can repair, apologize and stay; love includes mending.",
   "I am a safe place for myself first, and that changes every room I enter.",
 ],
 "Career & Purpose": [
   "My work is allowed to fit my life, not replace it.",
   "I can be ambitious without being at war with myself.",
   "What I build slowly, I get to keep.",
   "My ideas deserve daylight, not just a drafts folder.",
   "I ask for what the work is worth, with my voice steady.",
   "Purpose, for me, can look like ordinary days done with care.",
   "I am allowed to outgrow work that once fit perfectly.",
   "Progress in private still counts; I keep going where no one claps.",
   "I no longer need to rush what I am building.",
   "The skills I already carry are worth more than I have been charging.",
   "I can start before I feel ready; ready is often a result, not a requirement.",
 ],
 "Receiving": [
   "I am available for aligned opportunities.",
   "Thank you is a complete sentence, and I am practicing it.",
   "Help reaching me is not a debt; it is a current.",
   "I can receive without abandoning myself.",
   "Open hands hold more than clenched ones; I am unclenching.",
   "I let compliments land instead of returning them to sender.",
   "What arrives easily can still be deserved.",
   "I am allowed to accept the good thing without inspecting it for flaws.",
   "Support is not a loan against my independence.",
   "I say yes to what I asked for when it shows up.",
   "Receiving well is a way of honoring the giver, and I honor mine.",
 ],
 "Aligned Action": [
   "I honor my desire with action.",
   "My actions are beginning to match my intentions.",
   "One scheduled step outweighs ten spectacular plans.",
   "I move at the speed of my values, not my panic.",
   "Tiny and done beats grand and someday.",
   "My calendar is where my intentions learn to walk.",
   "I adjust the plan without abandoning the promise.",
   "Consistency is my quiet superpower, built one kept appointment at a time.",
   "I finish things now, imperfectly and on purpose.",
   "Every action I take is evidence for the woman I am becoming.",
   "I do the next thing, and the path keeps appearing under my feet.",
 ],
}

# The 32 card texts: 8 per card category, drawn from the families above.
CARD_SETS = {
 "Abundance": [
   "There is more than one way for good things to reach me.",
   "I can want more and be grateful at the same time.",
   "Enough is a place I can visit today, not only a finish line.",
   "Small surpluses count; I notice them and let them count.",
   "What I tend tends to grow, and I am tending my own field now.",
   "Plenty does not require my exhaustion as payment.",
   "I make room for a life that fits me.",
   "Abundance, for me, includes time, ease and people I can exhale around.",
 ],
 "Self-Concept": [
   "I do not have to audition for my own life.",
   "I keep small promises to myself, and they are adding up.",
   "My presence adds something before I produce anything.",
   "I belong in rooms I used to only clean up after.",
   "I am allowed to take up the space my life actually needs.",
   "I am someone I can rely on, and I have the receipts.",
   "Every action I take is evidence for the woman I am becoming.",
   "Good things suit me; I am practicing believing that.",
 ],
 "Courage & Action": [
   "Courage can be quiet and consistent.",
   "I can be afraid and in motion at the same time.",
   "Five percent braver, repeated, becomes a different life.",
   "Fear gets a seat in the car, never the wheel.",
   "I let my work be witnessed before it is perfect.",
   "Tiny and done beats grand and someday.",
   "My calendar is where my intentions learn to walk.",
   "I honor my desire with action.",
 ],
 "Receiving & Trust": [
   "I trust the next honest step.",
   "I am available for aligned opportunities.",
   "I can receive without abandoning myself.",
   "Thank you is a complete sentence, and I am practicing it.",
   "Open hands hold more than clenched ones; I am unclenching.",
   "What arrives easily can still be deserved.",
   "I say yes to what I asked for when it shows up.",
   "The next honest step is enough navigation for today.",
 ],
}

# The 12 wallpaper lines.
WALLPAPERS = [
 "I trust the next honest step.",
 "I am available for aligned opportunities.",
 "I can receive without abandoning myself.",
 "My actions are beginning to match my intentions.",
 "I no longer need to rush what I am building.",
 "I make room for a life that fits me.",
 "Courage can be quiet and consistent.",
 "I honor my desire with action.",
 "I do not have to audition for my own life.",
 "Enough is a place I can visit today, not only a finish line.",
 "I keep small promises to myself, and they are adding up.",
 "Every brave thing I have done was once the thing I avoided.",
]
