"""Tarot & Oracle Reflection — cards as mirrors, not verdicts."""

PAGES = [
    {
        "family": "education",
        "section": "Tarot & Oracle",
        "title": "Cards as Mirrors",
        "subtitle": "A reflective way to read, with any deck you already own",
        "toc": True,
        "wash": True,
        "blocks": [
            ("p", "Tarot and oracle cards will not tell you what is going to happen. In this workbook they do something more useful: they show you what you already think, feel and want, by handing your intuition an image to respond to. A card is a **mirror and a conversation starter**, never a verdict. Any deck works here, tarot or oracle, inherited or brand new, and this entire chapter is optional. If cards are not your thing, skip ahead; nothing later depends on them."),
            ("h2", "The first-impression practice"),
            ("steps", [
                ("Look before you read", "Turn the card over and stay with the image for three slow breaths before touching any guidebook."),
                ("Notice what rises", "A detail, a feeling, a memory, a face. Your first response is information about you, not about fate."),
                ("Consult the booklet last", "Read the printed meaning as one voice at the table, not the final word. Where it disagrees with your gut, get curious about the gap."),
            ]),
            ("h2", "Keeping interpretation notes"),
            ("p", "After each pull, jot four things: the date, your question, the card, and what you saw first. Over the weeks these notes become a private dictionary. You will start to recognize which images your mind reaches for when it is tired, brave, avoiding something, or ready."),
            ("callout", "The action takeaway habit", "Close every pull, however small, by writing one real-world step the card suggests. A reading that changes nothing was entertainment. A reading that moves your hands is practice."),
            ("quote", "A card cannot know your future. It can show you your mind."),
        ],
    },
    {
        "family": "exercise",
        "section": "Tarot & Oracle",
        "title": "The Clarity Pull",
        "subtitle": "One card to check in, three to move something",
        "blocks": [
            ("p", "Shuffle while holding a question that is honestly yours, not one you think you should ask. Then work through both readings below at whatever pace the day allows."),
            ("h3", "One card: today's mirror"),
            ("fields", ["The card I drew"]),
            ("prompt", "Before opening any booklet, what I noticed first in the image was:", 2),
            ("prompt", "Read as a mirror of my current season, this card points at:", 2),
            ("fields", ["One small step it nudges me toward"]),
            ("rule",),
            ("h3", "Three cards: Release, Receive, Act"),
            ("kv", [
                ("1 · Release", "What I am ready to set down this season."),
                ("2 · Receive", "What is quietly asking to be welcomed in."),
                ("3 · Act", "The single move that would honor both."),
            ]),
            ("note", "For each position, record the card, your first impression, and what it means to you today. End with the action, given a day on your calendar."),
            ("linesfill",),
        ],
    },
    {
        "family": "exercise",
        "section": "Tarot & Oracle",
        "title": "The Lion's Gate Eight-Card Spread",
        "subtitle": "A season reading in the shape of the date",
        "toc": True,
        "blocks": [
            ("p", "Lay the cards in a circle if you have the room, or in two rows of four. Move slowly: one card, one first impression, one line of meaning, before you turn the next."),
            ("kv", [
                ("1 · The Ground", "Where I actually stand as this season opens."),
                ("2 · The Door", "What is opening for me, or asking to be opened."),
                ("3 · The Weight", "What I am carrying that can now be set down."),
                ("4 · The Flame", "Where courage wants to move through me."),
                ("5 · The Gift", "What I am becoming ready to receive."),
                ("6 · The Practice", "The daily behavior that would build it."),
                ("7 · The Ally", "The support, person or resource already within reach."),
                ("8 · The Horizon", "What this season is quietly becoming."),
            ]),
            ("pi", "Record your notes card by card, or read the whole circle first and write the story it tells. Close by choosing one action from position six and giving it a date this week."),
            ("linesfill",),
        ],
    },
    {
        "family": "exercise",
        "section": "Tarot & Oracle",
        "title": "Spreads for the Life You Are Building",
        "subtitle": "Two compact layouts: your future self, and abundance",
        "blocks": [
            ("p", "These small spreads are positions only; bring your own rhythm to them. Image first, booklet last, and one concrete step written down at the end of every reading."),
            ("h3", "The future-self spread · four cards"),
            ("note", "Use this when you want counsel from the woman you are becoming."),
            ("bullets", [
                "**1 · Her morning:** how my future self begins an ordinary day",
                "**2 · Her standard:** what she no longer accepts or apologizes for",
                "**3 · Her secret:** what she knows that I am still learning",
                "**4 · Her invitation:** what she asks me to start practicing now",
            ]),
            ("lines", 4),
            ("h3", "The abundance spread · four cards"),
            ("note", "Use this to examine your relationship with money and plenty, not to predict income."),
            ("bullets", [
                "**1 · The Root:** my current story about money and enough",
                "**2 · The Leak:** where energy, time or resources drain away",
                "**3 · The Channel:** where more could realistically flow in",
                "**4 · The Steward:** how I care well for what I already have",
            ]),
            ("linesfill",),
        ],
    },
    {
        "family": "exercise",
        "section": "Tarot & Oracle",
        "title": "Spreads for Love and Work",
        "subtitle": "Reading your patterns, not other people",
        "blocks": [
            ("p", "Both layouts below look inward on purpose. Cards can illuminate your side of any dynamic; they cannot read another person's mind, and this workbook never uses them to try."),
            ("h3", "The relationship-pattern spread · four cards"),
            ("note", "For any recurring dynamic: romantic, family, friendship or work."),
            ("bullets", [
                "**1 · The Pattern:** what keeps repeating in my connections",
                "**2 · The Origin:** where I first learned this dance",
                "**3 · The Cost:** what the pattern quietly takes from me",
                "**4 · The New Step:** the response I want to practice instead",
            ]),
            ("lines", 4),
            ("h3", "The business-alignment spread · four cards"),
            ("note", "For work decisions, projects, or a venture you are weighing."),
            ("bullets", [
                "**1 · The Work:** what my work is really about right now",
                "**2 · The Fit:** where my current path matches my values",
                "**3 · The Friction:** where it grinds against them",
                "**4 · The Adjustment:** one concrete change worth testing",
            ]),
            ("linesfill",),
        ],
    },
]
