"""Vision Board & Visualization — values before images, action after both."""

PAGES = [
    {
        "family": "education",
        "section": "Vision & Visualization",
        "title": "See It Before You Search It",
        "subtitle": "Why the feelings come first and the pictures come second",
        "toc": True,
        "wash": True,
        "blocks": [
            ("p", "Most vision boards fail before the glue dries, because they are built backward. Open an app, search *dream life*, and you will assemble a collage of other people's lives: rented villas, strangers' weddings, a beige kitchen you have been shown four hundred times. It is beautiful, and none of it is yours."),
            ("p", "This chapter reverses the order. First you name the **feelings and values** you want more of, drawn from your own lived evidence. Only then do you go looking for images, and you keep only the ones that match something you chose on purpose. The board becomes a set of instructions to your attention instead of a mood."),
            ("h2", "Visualization as rehearsal"),
            ("p", "Mentally walking through a scene before you live it is rehearsal, the same tool performers and athletes use: it makes the unfamiliar feel navigable and primes you to notice relevant openings. It is not a substitute for doing. Kept brief, made sensory, and followed by one concrete step, a few minutes of rehearsal is a practical habit rather than a wish."),
            ("bullets", [
                "Keep it short: two or three minutes beats a drifting half hour",
                "Make it sensory: what you would see, hear, and do with your hands",
                "Rehearse yourself acting, not just receiving",
                "End every session by taking one small step while the scene is warm",
            ]),
        ],
    },
    {
        "family": "exercise",
        "section": "Vision & Visualization",
        "title": "Feelings First, Then a Word",
        "subtitle": "The values that will choose your images for you",
        "blocks": [
            ("p", "Before you look at a single picture, decide what the pictures are for. Work from memory, not from a list of impressive-sounding words: the feelings you want more of are ones you have already met."),
            ("h3", "Three desired feelings"),
            ("fields", ["First feeling", "Second feeling", "Third feeling"]),
            ("prompt", "One real memory where each of these feelings was already true for me:", 4),
            ("h3", "A word for the year ahead"),
            ("p", "Choose one word to sit at the center of your board. Audition a few before you commit."),
            ("fields", ["Candidate words I am weighing", "The word I am choosing"]),
            ("prompt", "On a hard day, I want this word to remind me that:", 3),
        ],
    },
    {
        "family": "exercise",
        "section": "Vision & Visualization",
        "title": "The Eight-Frame Plan",
        "subtitle": "One image idea for each area of your life",
        "toc": True,
        "blocks": [
            ("p", "These are the same eight life areas you have worked with throughout this book. For each one, sketch a quick image idea in words, then name the feeling it stands for. If a category is quiet this season, leave its row blank without apology."),
            ("bullets", [
                "Choose images where you are the subject, not the spectator",
                "Prefer scenes you could plausibly step into within a year or two",
                "If a picture impresses you but does not feel like yours, let it go",
            ]),
            ("table",
             ["Category", "Image idea", "Feeling it represents"],
             [["Wealth", " ", " "],
              ["Career", " ", " "],
              ["Love", " ", " "],
              ["Confidence", " ", " "],
              ["Home", " ", " "],
              ["Creativity", " ", " "],
              ["Wellness", " ", " "],
              ["Spirit", " ", " "]],
             [0.22, 0.44, 0.34]),
            ("prompt", "The frame I am most certain about, and why it feels like mine:", 3),
            ("note", "Overflow space: spare image ideas, and anything you are not yet sure belongs."),
            ("linesfill",),
        ],
    },
    {
        "family": "action",
        "section": "Vision & Visualization",
        "title": "Build the Board You Will Actually See",
        "subtitle": "A digital board that lives where your eyes already go",
        "blocks": [
            ("p", "A board rolled up behind the dresser does nothing. The version below lives on your phone, which means it gets seen dozens of times a day without any extra effort from you."),
            ("steps", [
                ("Collect", "Save images that match your eight-frame plan: your own photos first, then found images that pass the *is this mine* test."),
                ("Curate", "Cut the pile to about twelve. If everything on the board shines, nothing does."),
                ("Arrange", "In any free collage app, place your word of the year at the center and one image per life area around it."),
                ("Export", "Save the finished board as your phone wallpaper or lock screen, so glancing at your phone becomes the practice."),
            ]),
            ("callout", "From the bonus set", "This product includes a set of affirmation wallpapers. Pair one affirmation wallpaper from the bonus set with your board, one on the lock screen and one on the home screen, so word and image travel together."),
            ("prompt", "Each time this wallpaper catches my eye, the thought I want to practice is:", 2),
            ("aff", "What I look at daily, I move toward slowly."),
        ],
    },
    {
        "family": "action",
        "section": "Vision & Visualization",
        "title": "One Image, One Action",
        "subtitle": "The monthly check that keeps the board honest",
        "blocks": [
            ("p", "An image without an action is decoration. Pair every picture on your board with one behavior you can actually schedule, however small, so the board points at your calendar and not just your mood."),
            ("twocol", "Image on my board", "The action it is paired with", 5),
            ("h3", "The monthly check"),
            ("p", "On the same date each month, sit with the board and ask two questions of every image: *still true?* and *still mine?* Retire anything that belongs to an old version of you; an outdated board trains your attention on a life you no longer want."),
            ("table",
             ["Image", "Still resonates?", "Action taken this month"],
             [["1.", " ", " "],
              ["2.", " ", " "],
              ["3.", " ", " "],
              ["4.", " ", " "],
              ["5.", " ", " "],
              ["6.", " ", " "]],
             [0.4, 0.24, 0.36]),
            ("prompt", "What I am retiring from the board this month, and what earns its place:", 3),
            ("linesfill",),
        ],
    },
]
