# Abundance & Money -- content module for The Lion's Gate 8/8 Activation
# Exports PAGES for the layout engine in lg/engine.py. See STYLE_GUIDE.md.

PAGES = [
    {
        "family": "education",
        "section": "Abundance & Money",
        "title": "Abundance Is Wider Than Luxury",
        "subtitle": "Time, ease, connection and options count too",
        "toc": True,
        "wash": True,
        "blocks": [
            ("p", "Money is one currency. It is not the only one. An abundant life can also be measured in unhurried mornings, in people who answer when you call, in the ease of a body that is cared for, and in options: the quiet power of having more than one way forward. When this section says abundance, it means the whole ledger, not just the bank column."),
            ("h2", "How scarcity talks"),
            ("p", "Scarcity has a vocabulary: *always*, *never*, *everyone else*, *too late*, *not for people like me*. These words are not descriptions, they are conclusions, and conclusions close doors. It is worth listening for them, because scarcity narrows thinking. Under its influence you plan smaller, ask for less and stop noticing exits."),
            ("h2", "Receiving is a skill"),
            ("p", "Many generous women are terrible receivers. They deflect compliments, undercharge, split every check and turn help away at the door. Abundance work includes practicing the other half of the exchange: letting support, payment and kindness actually arrive."),
            ("callout", "Gratitude with your eyes open", "You can be grateful for what you have and still have real bills, real gaps and real worry. Gratitude is not denial. It is a wider camera angle, one that includes the good without cropping out the true."),
            ("p", "One boundary governs this whole section: manifestation is motivation for action, never a replacement for it. Nothing here promises income, and nothing here replaces professional financial guidance."),
            ("quote", "Abundance counts everything: the money, the minutes, the people, the choices."),
        ],
    },
    {
        "family": "exercise",
        "section": "Abundance & Money",
        "title": "Your Money Story",
        "toc": True,
        "blocks": [
            ("p", "Before you can rewrite a money story, it helps to read the one you inherited. Answer quickly; first drafts are the honest ones."),
            ("prompt", "My earliest memory involving money is:", 3),
            ("prompt", "Growing up, the messages I absorbed about money sounded like:", 3),
            ("note", "If a family message stirs something heavy, the Shadow section of this workbook holds the deeper inherited-belief work. This page only takes the inventory."),
            ("h3", "Today's check-in"),
            ("scale", "When I think about my money right now, my level of calm is"),
            ("prompt", "The feeling underneath that number, in a few unedited sentences:", 3),
            ("lines", 2),
        ],
    },
    {
        "family": "exercise",
        "section": "Abundance & Money",
        "title": "Looking Money in the Eye",
        "blocks": [
            ("p", "Financial avoidance is common and human: unopened envelopes, an app you never check, a number you would rather estimate than know. Avoidance feels like protection, but it quietly charges interest in worry."),
            ("prompt", "The money thing I have been avoiding looking at is:", 2),
            ("h3", "The ten-minute look"),
            ("steps", [
                ("Set a timer", "Ten minutes, once this week. When it rings, you are allowed to be done."),
                ("Look at one thing", "Open one statement or one balance. Just read it. No fixing yet."),
                ("Close it kindly", "Write one sentence about what you now know, then put it away."),
            ]),
            ("h3", "Financial visibility: know your numbers"),
            ("check", [
                "My monthly take-home amount",
                "My fixed monthly bills, listed in one place",
                "My debt balances and their interest rates",
                "My subscriptions, reviewed within the last 90 days",
                "What is in savings, even if the number is small",
                "The dates my key bills are due",
            ]),
            ("note", "This page is organization, not financial advice. And if buying something has become the fastest way to feel abundant for an evening, especially on credit, be gentle with yourself and slow those purchases down. Debt-funded proof of abundance costs more than it gives."),
            ("prompt", "After my first ten-minute look, the one sentence I wrote was:", 3),
        ],
    },
    {
        "family": "exercise",
        "section": "Abundance & Money",
        "title": "What the Money Is For",
        "blocks": [
            ("p", "A money goal without a value underneath is just a number, and numbers alone do not motivate for long. Connect each goal to what it protects or makes possible, and the goal starts pulling instead of nagging."),
            ("prompt", "If more money arrived in my life, what it would actually buy is (safety, options, rest, generosity, repair, something else):", 4),
            ("h3", "Three values-based money goals"),
            ("fields", [
                "A goal that buys me safety",
                "A goal that buys me options",
                "A goal that buys me rest or joy",
            ]),
            ("prompt", "The income or amount I catch myself wishing for, and the life change I am really asking it to deliver:", 4),
        ],
    },
    {
        "family": "exercise",
        "section": "Abundance & Money",
        "title": "Where Value Already Lives",
        "blocks": [
            ("p", "Money, earned ethically, comes from value: something you do, make or know that genuinely helps someone else. Before inventing a new self, inventory the one you already are. The second column matters most; what people ask you for is value they have already noticed."),
            ("twocol", "What I am good at", "What people ask me for", 6),
            ("prompt", "The overlap between my two columns that intrigues me most is:", 2),
            ("h3", "Three small money actions"),
            ("fields", [
                "One new-revenue action I could test this month",
                "One expense-awareness action (a bill to review, question or cancel)",
                "One financial-organization action (a folder, a list, an appointment)",
            ]),
        ],
    },
    {
        "family": "exercise",
        "section": "Abundance & Money",
        "title": "My Next Honest Money Move",
        "toc": True,
        "blocks": [
            ("p", "Choose the move that is most honest for where you actually are: not the flashiest, not the most impressive on paper, the one your gut has already quietly nominated."),
            ("prompt", "My next honest money move, and the date I will make it by:", 3),
            ("h3", "The believable-bridge affirmation builder"),
            ("p", "An affirmation only works if you can say it without arguing back. Start with the claim you wish were true, then build a bridge your nervous system will actually cross: *I am learning to*, *I am becoming*, *I am the kind of woman who is starting to*."),
            ("fields", [
                "The big claim I wish felt true",
                "A bridge version I can say without flinching",
                "Where this sentence will meet me daily (mirror, phone, kettle)",
            ]),
            ("aff", "I handle what is mine to handle, one honest move at a time."),
            ("lines", 2),
        ],
    },
    {
        "family": "action",
        "section": "Abundance & Money",
        "title": "Thirty Days of Prosperity Actions",
        "blocks": [
            ("p", "One action a week for four weeks. Small counts. An action can be a phone call, a cancellation, a price raised, a number finally known, an invoice finally sent. Write it, do it, mark it done."),
            ("table",
             ["Week", "Action", "Done"],
             [["Week 1", "", ""],
              ["Week 2", "", ""],
              ["Week 3", "", ""],
              ["Week 4", "", ""]],
             (0.16, 0.68, 0.16)),
            ("note", "If a week slips, do not double up and do not drop out. Just take the next week's action. In money habits, consistency beats intensity."),
            ("h3", "What shifted as I went"),
            ("lines", 8),
        ],
    },
]
